apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
 name: default-bgp-peering-policy
spec:
 nodeSelector:
   matchLabels:
     bgp-policy: default
 virtualRouters:
 - localASN: 64512
   exportPodCIDR: false
   neighbors:
    - peerAddress: '192.168.4.254/32'
      peerASN: 64512
    - peerAddress: '2a12:zzzz:yyyy::1/128'
      peerASN: 64512
   serviceSelector:
     matchExpressions:
       - {key: somekey, operator: NotIn, values: ['never-used-value']}
