# Source: external-dns/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: external-dns-lb
  namespace: "external-dns"
  labels:
    app.kubernetes.io/instance: external-dns-lb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: external-dns-lb
    app.kubernetes.io/version: 0.14.0
    helm.sh/chart: external-dns-6.31.6
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http
      port: 7979
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: external-dns-lb
    app.kubernetes.io/name: external-dns-lb
---
# Source: external-dns/templates/dep-ds.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-lb
  namespace: "external-dns"
  labels:
    app.kubernetes.io/instance: external-dns-lb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: external-dns-lb
    app.kubernetes.io/version: 0.14.0
    helm.sh/chart: external-dns-6.31.6
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: external-dns-lb
      app.kubernetes.io/name: external-dns-lb
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: external-dns-lb
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: external-dns-lb
        app.kubernetes.io/version: 0.14.0
        helm.sh/chart: external-dns-6.31.6
    spec:

      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: Always
        supplementalGroups: []
        sysctls: []
      affinity:
        podAffinity:

        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: external-dns-lb
                    app.kubernetes.io/name: external-dns-lb
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:

      automountServiceAccountToken: true
      serviceAccountName: external-dns
      containers:
        - name: external-dns-lb
          image: docker.io/bitnami/external-dns:0.14.0-debian-11-r9
          imagePullPolicy: "IfNotPresent"
          args:
            # Generic arguments
            - --metrics-address=:7979
            - --log-level=info
            - --log-format=text
            - --policy=upsert-only
            - --provider=cloudflare
            - --registry=txt
            - --interval=1m
            - --source=service
            # Cloudflare arguments
          env:
            # Cloudflare environment variables
            - name: CF_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: external-dns
                  key: cloudflare_api_token
                  optional: true
            - name: CF_API_KEY
              valueFrom:
                secretKeyRef:
                  name: external-dns
                  key: cloudflare_api_key
                  optional: true
            - name: CF_API_EMAIL
              value: ""
          envFrom:
          ports:
            - name: http
              containerPort: 7979
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1001
            seLinuxOptions: null
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits: {}
            requests: {}
          volumeMounts:
      volumes:
---
